### ISSUE TITLE
Conflicting case-insensitive resource filenames

### ISSUE THREAD

**Issue by falkTX** [EaterOfSheep/sheepextratone#5]
Hi there.
Just noticed that your modules, when installed on macOS and Windows (or any other system with case-insensitive filenames) will have issues due to how the files are named.
You have "screw.svg" and "Screw.svg" for example. Only one of those is possible on Windows and default macOS installs.
So the plugin ends up in undefined behaviour regarding which files are actually used.

![image](https://user-images.githubusercontent.com/1334853/145682911-801e45aa-02f6-4651-9ee6-9dab429d90e8.png)

If they are meant to be the same file, the wrong ones should be deleted from the repo.

**Comment by falkTX** [comment]
According to https://github.com/EaterOfSheep/Extratone/blob/main/src/plugin.hpp#L27 the correct file is `screw.svg`, so the `Screw.svg` can be deleted..?

**Comment by offthesky** [comment]
responding to dromer from issue #80:

> These are not duplicate filenames, but it seems windows case-insensitivity is being a PITA?
Is there an actual issue you are seeing with these?

upon extracting via winrar i just chose yes to all, it automatically used the larger files (so it picked screw.svg & XtrtnKnob.svg). i've loaded up all the modules and nothing looks amiss. haven't had a chance to really use them yet though.

**Comment by EaterOfSheep** [comment]
Thank you very much! This explains why, in videos, other users didn't have my custom-knob graphics.
