### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [EaterOfSheep/sheepextratone#7]
Just a quick question, as I don't see it mentioned anywhere.
Your project is licensed under GPL-3.0-or-later, but does that include the graphics too? Or are those supposed to be in a different license?
Thanks!

**Comment by EaterOfSheep** [comment]
Yes, graphics are intended to be under GPL-3.0-or-later. Does this have any troublesome consequences for you?

**Comment by falkTX** [comment]
No, this is quite fine, just unusual when it comes to artwork licensing.
Thanks for the quick reply!
