### ISSUE TITLE
Question on Mononeura

### ISSUE THREAD

**Issue by firolightfog** [EaterOfSheep/sheepextratone#8]
I'm confused. The BASE is switched off. Am I expected to hear the CLOCK if all four blue LEDs are off? (I mean that all four muted by the blue, purple, green, and white CVs.)

<img width="91" alt="image" src="https://user-images.githubusercontent.com/34127628/152607239-9a4f2901-93a0-4257-bdc0-f6a1f1abdcf1.png">

**Comment by EaterOfSheep** [comment]
Yes. The base parameter is for the 'Out' outputs. 
Admittedly, a lot of the modules have some quite arbitrary design choices behind them which I should probably add alternate modes for when I get back to developing. I'm sorry for the recent inactivity - I will be back!
